apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 941377142074.dkr.ecr.ap-south-1.amazonaws.com/inventory-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: inventory
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
